dist: xenial
language: python
python:
- 3.6
- 3.7

before_install:
- pip install --upgrade pip
- pip install poetry

install:
- poetry install

script: make test

before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASS

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
    repo: {{cookiecutter.user_name}}/{{cookiecutter.project_name}}
    python: 3.7

after_success:
- codecov
